name: CI

on: [push]

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25.1.1'
          elixir-version: '1.14.1'

      - run: |
          mix deps.get
          mix compile
          mix esbuild default

      - working-directory: playwright/
        run: |
          npm ci
          npx playwright install --with-deps
          npx playwright test
